export const metadata = {
  title: 'Services - AMX UAV',
  description: 'AMX UAV aerial mapping, VR, agriculture, and system developer services',
};

const services = [
  {
    id: 'aerial-mapping',
    title: 'AERIAL MAPPING',
    img: '/img/services-aerial mapping.png',
    desc: 'Support with an experienced team, AMX UAV provides an accurate and precise spatial data generated by our mapping drone. We have a standby team for rapid deployment.',
  },
  {
    id: 'vr',
    title: 'AUGMENTED/\nVIRTUAL REALITY',
    img: '/img/services-vr.png',
    desc: "What's special is we can visualize spatial data interactively, using virtual reality (VR). Very useful for tourism promotion, inspection, and monitoring needs.",
  },
  {
    id: 'agriculture',
    title: 'AGRICULTURE MANAGEMENT SYSTEM',
    img: '/img/services-agriculture.jpg',
    desc: 'Optimize agriculture with advanced UAV monitoring and sprayer drones, delivering precise data to streamline your irrigation and harvest.',
  },
  {
    id: 'system-developer',
    title: 'SYSTEM DEVELOPER',
    img: '/img/AMX-GCS.jpg',
    desc: 'We develop custom autonomous control ecosystems to maximize quad rotor tailsitter drone performance. We provide integrated flight management solutions to ensure seamless autonomous coordination and high-efficiency mission execution.',
  },
];

export default function ServicesPage() {
  return (
    <main className="services-container">
      {services.map((service) => (
        <div className="service-wrapper" key={service.id} id={service.id}>
          <div className="service-image-box">
            <img src={service.img} alt={service.title} />
          </div>
          <div className="service-block">
            <h1 className="service-title">{service.title}</h1>
            <p>{service.desc}</p>
          </div>
        </div>
      ))}
    </main>
  );
}